### ISSUE TITLE
Ubuntu 16.04 LTS Markdown Preview Errors

### ISSUE THREAD

**Issue by vladipus** [jpfleury/gedit-markdown#15]
Fresh install, gedit 3.18.3. Getting the following warnings and errors during the startup:

```
/home/vladius/.local/share/gedit/plugins/markdown-preview/__init__.py:21: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gdk, Gtk, Gedit, GObject, WebKit
Traceback (most recent call last):
  File "/home/vladius/.local/share/gedit/plugins/markdown-preview/__init__.py", line 113, in do_activate
    self.addMarkdownPreviewTab()
  File "/home/vladius/.local/share/gedit/plugins/markdown-preview/__init__.py", line 139, in addMarkdownPreviewTab
    panel.add_item(self.scrolledWindow, "MarkdownPreview", _("Markdown Preview"), image)
AttributeError: 'Stack' object has no attribute 'add_item'
Traceback (most recent call last):
  File "/home/vladius/.local/share/gedit/plugins/markdown-preview/__init__.py", line 128, in do_update_state
    self.actionGroup1.set_sensitive(self.window.get_active_document() != None)
AttributeError: 'MarkdownPreviewPlugin' object has no attribute 'actionGroup1'
Traceback (most recent call last):
  File "/home/vladius/.local/share/gedit/plugins/markdown-preview/__init__.py", line 128, in do_update_state
    self.actionGroup1.set_sensitive(self.window.get_active_document() != None)
AttributeError: 'MarkdownPreviewPlugin' object has no attribute 'actionGroup1'
Traceback (most recent call last):
  File "/home/vladius/.local/share/gedit/plugins/markdown-preview/__init__.py", line 128, in do_update_state
    self.actionGroup1.set_sensitive(self.window.get_active_document() != None)
AttributeError: 'MarkdownPreviewPlugin' object has no attribute 'actionGroup1'
Traceback (most recent call last):
  File "/home/vladius/.local/share/gedit/plugins/markdown-preview/__init__.py", line 128, in do_update_state
    self.actionGroup1.set_sensitive(self.window.get_active_document() != None)
AttributeError: 'MarkdownPreviewPlugin' object has no attribute 'actionGroup1'
Traceback (most recent call last):
  File "/home/vladius/.local/share/gedit/plugins/markdown-preview/__init__.py", line 128, in do_update_state
    self.actionGroup1.set_sensitive(self.window.get_active_document() != None)
AttributeError: 'MarkdownPreviewPlugin' object has no attribute 'actionGroup1'
Traceback (most recent call last):
  File "/home/vladius/.local/share/gedit/plugins/markdown-preview/__init__.py", line 119, in do_deactivate
    manager = self.window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'

```

**Comment by vineeshvs** [comment]
Doesn't work for me also. Using 3.18.3 version of gedit!!!

**Comment by Kitzberger** [comment]
See pull request #9

**Comment by darkdragon-001** [comment]
This issue is fixed in my fork: https://github.com/darkdragon-001/gedit-markdown/

Please test the latest release. Pull requests are always welcome!

**Comment by jpfleury** [comment]
Fixed in latest release.
